background = 00000B
foreground = FDFBDE
cursor-color = ECC89A
selection-background = FDFBDE
selection-foreground = 00000B

palette = 0=#00000B
palette = 1=#BB343D
palette = 2=#A47040
palette = 3=#618671
palette = 4=#AD7399
palette = 5=#859EB6
palette = 6=#BCB779
palette = 7=#F4F1C8
palette = 8=#ABA98C
palette = 9=#F94551
palette = 10=#DA9555
palette = 11=#81B297
palette = 12=#E799CC
palette = 13=#B1D3F2
palette = 14=#FAF4A1
palette = 15=#F4F1C8
