# Hyprland with colors from wallust
# The
# You can use this template by adding the following to wallust.toml:
# hypr = { src = "hyprland-colors.conf", dst = "~/.config/hypr/colors.conf" }
# and then on hyprland.conf:
# source = ~/.config/hypr/colors.conf
#13151A


$foregroundCol = 0xff
$backgroundCol = 0xff
$color0 = 0xff
$color1 = 0xff
$color2 = 0xff
$color3 = 0xff
$color4 = 0xff
$color5 = 0xff
$color6 = 0xff
$color7 = 0xff
$color8 = 0xff
$color9 = 0xff
$color10 = 0xff
$color11 = 0xff
$color12 = 0xff
$color13 = 0xff
$color14 = 0xff
$color15 = 0xff
general {
    # Here we use `saturate` filter to have more vibrant colors,
    # not matter the scheme, since the border should seek the attention
    col.active_border = rgb(010F22) rgb(242D0C) rgb(630D0F) rgb(186427) rgb(8E4816) rgb(B18E2F)
    # color0 is almost the same as the background color,
    # by putting ee as the alpha, it makes it 100% transparent
    col.inactive_border = rgba(3A3C42ee)
    bezier = linear, 0.0, 0.0, 1.0, 1.0
}

