#!/bin/sh

SELECT="$( echo -e "$(tmux list-sessions -F "#{session_name}")\nnew" | rofi -dmenu -theme ~/.config/rofi/style.rasi -p "tmux")" 

if [[ "$SELECT" == "new" ]]; then
    NEWNAME="$(rofi -dmenu -theme ~/.config/rofi/style.rasi -theme-str 'listview { scrollbar: false; lines: 0; }' -p "Name of tmux session")"
    if [[ -n "$NEWNAME" ]]; then
        ghostty -e tmux new -s $NEWNAME
    fi
elif [[ -n "$SELECT" ]]; then
    ghostty -e tmux attach -t $SELECT
fi

